### PR TITLE
Added flow charts and some text

### PR DESCRIPTION
**Pull request by handwerkerd**
@marco7877 created some flow charts of the decision trees. I tweaked them and added them to the documentation with some text.

I think I've also added @marco7877  as a co-author in the [75eb098](https://github.com/jbteves/tedana/pull/44/commits/75eb0989faef6865119d8ad12bd5a8253a5eee22) commit, but someone should confirm I did this correctly.

Changes proposed in this pull request:

- decision tree flow charts added
- text added to multiple places that links to the flow charts

I spent way too long trying to get the flow charts into svg files rather than png. The svg files loaded in my browser, but something in my conversion pipeline garbled the pdf file that was created from the LaTeX files. I think the png files are ok, but if anyone has any ideas, I can try to switch back to svg.

@dowdlelt and @n-reddy could you to look over these new parts of the documentation?

### CODE REVIEW

**Comment by handwerkerd** [comment]
I'm sure something else will turn up, but, as of now, this was the last thing I planned to add to this PR before saying it's ready to merge!

**Comment by handwerkerd** [comment]
The RTD build is failing https://readthedocs.org/projects/tedana/builds/20384330/ It looks like it's looking for a `setup.py` that no longer exists. I think this is our first RTD change since changing the package manager. Maybe some cache on the RTD side also needs to be refreshed. Any ideas @tsalo, @jbteves?

**Comment by tsalo** [comment]
I've been seeing the same problem in several repos. James Kent has a fix in the NiMARE repo: https://github.com/neurostuff/NiMARE/pull/797

**Comment by handwerkerd** [comment]
That solved the rendering problem. Thank you!

I've come across one other issue for @tsalo or @jbteves We created a file named `building decision trees.html` Every other file used underscores, so I changed it to `building_decision_trees.html`. As far as I can tell, I changed all references to the older name in the repo & every renders perfectly locally.

On the remote build, if you start at https://tedana--756.org.readthedocs.build/en/756/ and click on `Understanding and buliding a component selection process` in the contents bar, it is a dead link to the older file name. If you start at https://tedana--756.org.readthedocs.build/en/756/index.html or any other page, then the same link on the contents bar renders correctly. I'm assuming this is some weird cached info, but I'm not sure whether or not it will resolve itself when we merge. Any ideas?

**Pull request merged**
