### PR TITLE
Drop Python 3.6 and 3.7 support

### PR DESCRIPTION
**Pull request by tsalo**
Closes https://github.com/ME-ICA/tedana/issues/939 (I'll need to close manually).

Changes proposed in this pull request:

- Drop 3.6 and 3.7 mentions, environments, tests, etc.
- Make pandas 2.0.0 the minimum version.

### CODE REVIEW

**Comment by handwerkerd** [comment]
I just checked and this looks fine. I am concerned about pandas 2.0 since that puts people on the bleeding edge of pandas (April 2023 release) and even the breaking change that created this issue was a December 2022 release. For people who use a different environment for each software, this won't be an issue. Still, there are a bunch of breaking pandas changes in the last year and this will cause headaches for people who use the same python environment for multiple things.

Given we currently have a fix for the pandas version issue in the code, I'd lean towards bumping up the minimum python version, but not the pandas version. (Irony noted that the pandas breaking change is what motivated this PR in the first place) 

@tsalo @eurunuela Thoughts?

**Comment by eurunuela** [comment]
I would lean towards making 2.0.0 the minimum pandas version.

DTM is already a big enough (breaking) change, that bumping up the minimum pandas version seems like it could be part of it too.

**Comment by handwerkerd** [comment]
@tsalo, As part of #42, which I just merged, I lined JT_DTM up with Main. I was about to merge this PR but because of https://github.com/jbteves/tedana/blob/b06f65a009addeedc0bef766070bab6d1b5a7be5/tedana/io.py#L340-L345 in `io.py` there's a merge conflict. Since this is your branch, I figured it's better/easier for you to remove the conflict & then merge. If you don't have merge authority, let me know when it's ready to merge and I'll merge.

(Also, I merged #42 because I want to get this done and don't want a bunch of interconnected PRs sitting open, but I wouldn't mind another pair of eyes checking to make sure I didn't mess anything up.)

**Comment by handwerkerd** [comment]
@tsalo I just realized `ci/circleci: unittest_37 Expected — Waiting for status to be reported ` is hanging because we no longer have py37. I suspect there's something on the circleCI end that needs to be refreshed. Can you figure this out?

**Comment by tsalo** [comment]
The reason is we have a branch protection rule. I'll disable it.

**Comment by tsalo** [comment]
I think it should be good now.

**Pull request merged**
